### ISSUE TITLE
Tier App not working (FirebaseAuth)

### ISSUE THREAD

**Issue by Romern** [microg/android_packages_apps_GmsCore#1013]
In the Tier scooter app:
https://play.google.com/store/apps/details?id=com.tier.app&hl=de
I cannot register. The API requires a Firebase token, and when entering the phone number while registering it goes into an infinite loading loop and the logcat only shows:
```
02-06 17:25:19.165 10207 10207 I BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@43193af

```
This is probably related to https://github.com/microg/android_packages_apps_GmsCore/issues/756 and https://github.com/microg/android_packages_apps_GmsCore/issues/842 . 
I tried enabling Google device registration and Google Cloud Messaging, but it does not help.

EDIT: More logcat stuff (contains a few more firebase errors, but no exceptions (at least not from firebase)): https://gist.github.com/Romern/1857d4cfba76218151e4141c82640717

**Comment by wedza** [comment]
The "[7 Wonders](https://play.google.com/store/apps/details?id=com.rprod.sevenwonders)" app does not allow to log in into an account when microG is installed. When I checked the logs a few months ago, this was also was an issue related to `FirebaseAuth `function.

**Comment by mar-v-in** [comment]
Login into Tier app is fixed in c3bfb63f27c116d21ba7b2b87629e36573d4a59e.

**Comment by unixfox** [comment]
I'm still getting the infinite loop screen after updating to microg v0.2.13.203915? Is it normal? Do I've to enable something?

The self check in Microg has everything ticked. Google Device registration, Google Cloud messaging and Google safetyNet are ON.

**Comment by mar-v-in** [comment]
@unixfox have you granted the permisson to draw over other apps? Do you see a loading screen being displayed (and potentially recaptcha) when logging into Tier?

**Comment by unixfox** [comment]
@mar-v-in Thank you for your quick reply.

> have you granted the permisson to draw over other apps?

For the tier app? I don't see any permission for drawing over other apps in the settings of the app.

> Do you see a loading screen being displayed (and potentially recaptcha) when logging into Tier?

After the first two dialogs ("sign in to start" and "where are you"), I just see this loading screen and it stays like this forever:
![Screenshot_20201027-175854_TIER_1](https://user-images.githubusercontent.com/4016501/97327952-68948d80-186d-11eb-8a64-cf4b904f80ba.png)

**Comment by mar-v-in** [comment]
So you are not even reaching the point where you have to enter your phone number, which means Firebase Auth isn't the culprit here.

Have you checked if there is anything logged in logcat? Are you using any kind of firewall?

**Comment by unixfox** [comment]
I just fixed the issue, it was my custom rom not giving any GPS signal. Sometimes it does that and I've to reboot multiple times in order to have it working again.

Anyway thank you for spending the time of replying to my comments and sorry for bothering you with an issue that was in fact not related to microg.

**Comment by Acipenser** [comment]
I have a similar problem in LineageOS with microG (0.2.22.212658) when I try to register in Tier.

I can type in my phone number and click on continue. It opens the browser then with a connection to `https://consumer-app-release.firebaseapp.com/__/auth/handler?apiKey=...`. After being led back to the app an error occurs :

`At the moment we can not send you a code. Please try in a few minutes.`

Everything is checked in the microG self test and I activated Cloud Massaging and Google SafetyNet.
