### ISSUE TITLE
Whisper(.sh) app partially not working.

### ISSUE THREAD

**Issue by SolAZDev** [microg/android_packages_apps_GmsCore#1046]
I've noticed that the Whisper app works only partially. (At least for me). Whisper's a anon social network that doesn't use User accounts, instead it generates a profile (if one doesn't exist yet) and you have the option (though the app recommends it, and you cannot see other's complete profile) to set your Age range and location. You can also change your 'name' but thats not part of the issue.

The issue is, most parts of the app work, you can see your **local** posts, you can _kinda_ reply, you can join groups and see their posts as well. However, whenever you make a post, reply to a post or send a message, your location; which is already set (and thus read) remains "Somewhere" as in, unset, and thus it remains invisible to the recipients. Basically you can see whats up, but nobody can see whatever you do, and thus renders the whole thing unusable (As a social network end user anyway)

I've tried sending a report to the devs through the app's report system, sadly their official support page is down (503'd), so I decided to report it here. I've included the catlog of very light use. I can provide more if requested.

[2020-04-16-23-34-57.txt](https://github.com/microg/android_packages_apps_GmsCore/files/4490857/2020-04-16-23-34-57.txt)

Thank you for taking a look at this issue btw.

**Comment by Axolord** [comment]
This issue will probably be resolved with the new unifiedNlp version, that @mar-v-in is currently working on. At the moment there are many problems with network location (espacially with android 10)

**Comment by SolAZDev** [comment]
@Axolord  thanks for replying. Though I fear the use of FireBase might also be a problem

**Comment by SolAZDev** [comment]
Hello once again. So after a while I tried this again, and noticed it's still not working, despite firebase messaging being fully implemented, and location having no issues. Syntoms are the same, you can see your own posts and messages, but only you.

The log can be found here. https://termbin.com/on0o -- if there is anything I can do to help I'd like to do so.
