### ISSUE TITLE
eBay Kleinanzeigen

### ISSUE THREAD

**Issue by m54fjt6910tt3o948b1zi840oanas5uty4j3nq2** [microg/android_packages_apps_GmsCore#1151]
**ROM:**
lineage-17.1-20200827-microG-whyred

**GmsCore:**
0.2.11.202414 (built-in)

**eBay Kleinanzeigen:**
7.3.1 (as per https://github.com/microg/android_packages_apps_GmsCore/wiki/Problem-Apps)

### Steps to reproduce:
1. Select "Confirm new apps" in microG settings
2. Open eBay Kleinanzeigen
- **microG Services Core crashes** and **eBay Kleinanzeigen does not register for push notifications** (view [log](https://github.com/microg/android_packages_apps_GmsCore/files/5137837/2020-08-27-08-46-05.txt))
3. Deselect "Confirm new apps" in microG settings
4. Open eBay Kleinanzeigen
- **eBay Kleinanzeigen registers for push notifications**
5. Update eBay Kleinanzeigen to 11.16.0 (latest at the time of writing)
6. Open eBay Kleinanzeigen
- **eBay Kleinanzeigen freezes** (view [log](https://github.com/microg/android_packages_apps_GmsCore/files/5137869/2020-08-27-17-44-38.txt))

**Comment by hallogallo** [comment]
I am experiencing the same problem with app version **11.17.0** and **Havoc-OS-v3.7.-20200808-hero2lte-Unofficial.**
I did not select/deselect "confirm new apps", I just set up microG, installed eBay Kleinanzeigen and that already lead to a semi-freeze, I can still expand the side menu on the left but everything else does not react.

log file (filtered by loglevel error):
[2020-09-02-12-04-40.txt](https://github.com/microg/android_packages_apps_GmsCore/files/5161568/2020-09-02-12-04-40.txt)

**Comment by m54fjt6910tt3o948b1zi840oanas5uty4j3nq2** [comment]
I did some more testing and found that, for now, app version 11.7.0 is the last one that registers for push notifications and does not freeze. I updated the wiki accordingly.

**Comment by starbrights** [comment]
Same here LOS17.1 and Ebay Kleinanzeigen crashes. Go back in time with the app - in 11.0.0 it still works.

**Comment by gitfineon** [comment]
Confirm! There is still an issue with 'eBay Kleinanzeigen'  newer than app version 11.7.x **but newer can work, too!**

**ROM:**
lineage-17.1-20201202-microG-bardock

**GmsCore:**
0.2.14.204215 (built-in)

**Issue Description:**
The content loads and is scrollable but no reaction touching the menu, search bar or notification icon. So the upper part seems to be freezed. I haven't turned on the 'Confirm new apps' feature but the list of recent apps is cleared then. On my device the side was not expandable.

At first I tried the latest version (12.6.0.21259) from Aurora Store.
And then several from apkmirror, which I installed with [SAI](https://github.com/Aefyr/SAI)
'com.ebay.kleinanzeigen_11.8.1-16985_minAPI21(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk'
'com.ebay.kleinanzeigen_11.16.0-19069_minAPI21(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk'
'com.ebay.kleinanzeigen_11.17.0-19518_minAPI21(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk'
 com.ebay.kleinanzeigen_11.18.0-19843_4arch_3dpi_2lang_4228717ede3fb274a9248a1ad341bb6a_apkmirror.com.apks
'com.ebay.kleinanzeigen_11.18.0-19843_minAPI21(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk'
'com.ebay.kleinanzeigen_12.0.0-19980_minAPI21(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk'
 com.ebay.kleinanzeigen_12.6.0-21259_4arch_3dpi_2lang_c9a6c78aa6ad2297f01c742397fac347_apkmirror.com.apks
'com.ebay.kleinanzeigen_12.6.0-21259_minAPI21(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk'
All of them have the Tag 'Android 5.0+' [Lollipop, API 21]

I converted the *.apkm files with [unapkm](https://github.com/souramoo/unapkm) to *.apks, which makes the splitted packages installable with [SAI](https://github.com/Aefyr/SAI)

**Version 11.7.0-16703 is the last with tag 'Android 4.4+'** [Kitkat, API 19 / Target: Android 10 (Q, API 29)] **and still works!**
 com.ebay.kleinanzeigen_11.7.0-16703_4arch_3dpi_2lang_a93d93d3731ecce6e896787ca85edfbe_apkmirror.com.apks

**But now the good news:**
After I logged in with version 11.7.0, I started to write this post and read the post from @hallogallo that her side menu was expandable. So I updated to version 12.6.0-21259 (install without deinstallation) to try if sliding from left (instead of the menu button) works for me, too. The app wanted me to consent the GPDR (DSGVO) stuff again but this time I selected the button to customize and then saved with the default selection and holy cow it just works!

Maybe this helps to identify what might cause the issue. Thank you, keep up the good work!

**Comment by starbrights** [comment]
Any news here? At the moment the only workaround seems to stick at an old version like 11.0.0

**Comment by gitfineon** [comment]
Just gave Version 12.8.0 a try ... but still the same issue!
@starbrights mentioned version 11.0.0, which is from December 2019 ... crashes on my device!
Latest version working is still `com.ebay.kleinanzeigen_11.7.0-16703`
If your are using Aurora store, the easiest way is going to 'manual download' and type 16703.
Recently I found a new issue with this old version: The (notification) bell menu does not open any more, although push notifications still work.

**Comment by polarbergpotato** [comment]
For me, 11.7.0 and 11.0.0 both do work but Not the push nottifications. I have a Oneplus 3 with Android 10 and LineageOS 17.1 with microG (0.2.17.204717).
I sadly did not find a way to make the ebay Kleinanzeigen notifications work.

**Comment by coxtor** [comment]
This may not be an ideal solution, however this workaround works good enough for me for now: 

The latest version from the aurorastore 12.14.0 (23261)  works without issues, if you install the app to a work profile using the free and open source app "shelter". I believe this works, because the work profile has no google services installed at all, thus, for some reason, not causing the app to freeze at all. 
Hope this helps.

**Comment by polarbergpotato** [comment]
> This may not be an ideal solution, however this workaround works good enough for me for now:
> 
> The latest version from the aurorastore 12.14.0 (23261) works without issues, if you install the app to a work profile using the free and open source app "shelter". I believe this works, because the work profile has no google services installed at all, thus, for some reason, not causing the app to freeze at all.
> Hope this helps.

Thanks for the infos, though I am wondering if the notifications do work within the shelter?

**Comment by coxtor** [comment]
Notifications don't work at all as the rely on the non-present google services. You have to open the app in order to receive updates. The Bell at the top right works though.

**Comment by gitfineon** [comment]
Hey @coxtor can you give us some more details on what is working for you and on which Device/ROM/Version?

As mentioned before, (push) notifications work for me with the old `11.7.0-16703` build 

- using microG version `0.2.18.204214` bundled in the 17.1 OTA image from lineage.microg.org
- without G-account, but device registration and cloud messaging registered

but the notification bell of this old build doesn't work anymore.

Using a more recent version still behaves like I described it above. The behavior doesn't change for me using the work profile with shelter version 1.6. The green top bar is not usable after once the app quit. No matter the OS quit the app, or I did it by swiping up the app in the recent apps view, it doesn't work after that until app data cleanup. I also tried the 'auto-freeze' feature of Shelter, which makes it a bit more reliable the app doesn't quit unintentional, but not a really a acceptable workaround.

@polarbergpotato In general, push notifications within the work profile can work, if cloud messaging is configured for the coresponding microG settings.

**Comment by coxtor** [comment]
@gitfineon 
Sure, essentially I have nothing enabled in microG (see picture) on version 0.2.19.211515 using Rattlesnake OS on Android 11.
For me everything except Notifications is working - for obvious reasons.  
I am using shelter 1.6 with no extra configuration.
Ebay Version: 12.14.0 (23261)-a
Closing reopening, using the bell, chat - even payments work well. 
![kleinanzeigen](https://user-images.githubusercontent.com/7712562/119558043-3b777180-bda1-11eb-97e7-8d8437c33aeb.png)

Using Ebay outside the work profile causes my phone to crash entirely - I need to force shutdown using the power button.

**Comment by gitfineon** [comment]
Oh wow, quick answer, interesting OS and even worse behavior. Does your phones has hardware/sensor home button? Because the app also freezes on my device, but I'm able to quit by double tap on home (sensor button) to bring up app launcher and then tap 'recents' and swipe away the app.

Wanted to try if it depends on the system language, but according to your screenshot, using German as system language doesn't solve the issue.

Just found out that the old OnePlus One (armv7l) running LineageOS 16.0  (2020-06-24 build) with microG version `0.2.10.19420` runs the most recent version of eBay Kleinanzeigen (12.15.0) without any issues!!! 
- base.apk
- split_config.armeabi_v7a.apk
- split_config.xxhdpi.apk
- split_config.de.apk

**Comment by coxtor** [comment]
You caught me at the right moment ;) . Definitely an interesting behavior. So it does not appear to be a language issue then. I just tested your setup and unfortunately for me the issue persists: Total meltdown on my personal profile and on shelter it works flawlessly (v 12.15.0) .  The meltdown is in fact very interesting I have not seen that behavior before: I can get to recents using software buttons/gestures, however interacting with the OSes UI e.g.  "kill all apps" simply does not work. Neither does opening the settings from the notification menu. Logcat doesn't show anything exciting though. Anyway - nice to hear that it appears to be working for you!

**Comment by polarbergpotato** [comment]
> Hey @coxtor can you give us some more details on what is working for you and on which Device/ROM/Version?
> 
> As mentioned before, (push) notifications work for me with the old `11.7.0-16703` build
> 
>     * using microG version `0.2.18.204214` bundled in the 17.1 OTA image from lineage.microg.org
> 
>     * without G-account, but device registration and cloud messaging registered
> 
> 
> but the notification bell of this old build doesn't work anymore.
> 
> Using a more recent version still behaves like I described it above. The behavior doesn't change for me using the work profile with shelter version 1.6. The green top bar is not usable after once the app quit. No matter the OS quit the app, or I did it by swiping up the app in the recent apps view, it doesn't work after that until app data cleanup. I also tried the 'auto-freeze' feature of Shelter, which makes it a bit more reliable the app doesn't quit unintentional, but not a really a acceptable workaround.
> 
> @polarbergpotato In general, push notifications within the work profile can work, if cloud messaging is configured for the coresponding microG settings.

Thanks a lot! I did not know about the cloud messaging option in the microG Settings. Now push notifications do work with the version 11.7, though I had to do the following as described [here](https://forum.fairphone.com/t/issues-with-push-notifications-on-the-lineageos-microg-version/69902):
```
    Delete cache and data of microG Services Core and reboot.

    Activate Device Registration in microG and reboot.

    Activate Cloud Messaging and reboot.

    Delete data and cache (or reinstall) of apps that should use GCM and start them.

    It worked.
```

**Comment by Pokemetti** [comment]
For me, everything works (no problems with registration for gcm) but the app is unusable when opening. What works for me is to use the Android 7 shortcuts (where you long press the app to get to a specific activity quickly) to open the app on Notifications or Favorites. That way I have no issues right now! Using Android 9 OneUI.

**Comment by ale5000-git** [comment]
Try to update microG to v0.2.22.212658

**Comment by Pokemetti** [comment]
But I'm already on that version! Forgot to mention, this is the latest eBay Kleinanzeigen app version working with that workaround, since Notifications can't really be used on the 11.7 version anymore. This issue I found a workaround for doesn't seem to have been fixed in any microG version, as I have had this issue on multiple devices with multiple OS versions and the latest microG.

**Comment by phrogg** [comment]
I just recently installed microg and also kleinanzeigen I can confirm with the newest version from f-droid (v0.2.22.212658) it does not work unfortunately.

**Comment by Pokemetti** [comment]
I've experimented a bit more and found that for me only the start page is problematic, even when first opening through shortcuts, but the other tabs/activities all work on my phone. Strange that it isn't working on yours. On Android 10 I could already bypass the start page if I was quick enough and opened a different  tab/activity right after launch, but it wasn't consistent.

**Comment by phrogg** [comment]
> 

I've tried this right now, with the same version and for me this does not work. The app crashes on startup. I've also tried the newest version does not work as well unfortunately...

**Comment by phrogg** [comment]
> This may not be an ideal solution, however this workaround works good enough for me for now:
> 
> The latest version from the aurorastore 12.14.0 (23261) works without issues, if you install the app to a work profile using the free and open source app "shelter". I believe this works, because the work profile has no google services installed at all, thus, for some reason, not causing the app to freeze at all. Hope this helps.

I've tried this right now, with the same version and for me this does not work. The app crashes on startup. I've also tried the newest version does not work as well unfortunately...

**Comment by obifur** [comment]
It works exactly like @coxtor mentioned. But after installing shelter and Kleinanzeigen at work profile it is important to:
- deactivate microG in work profile
- it may also be necessary to delete data & cache of Kleinanzeigen within work profile

Now it will always complain that google is needed - just deactivate this notification and it works perfectly.

**Comment by Axolord** [comment]
ebay kleinanzeigen seems to be working fine for me with the new microG update. Just updated ebay kleinanzeigen and content loads, etc.

**Comment by phrogg** [comment]
> ebay kleinanzeigen seems to be working fine for me with the new microG update. Just updated ebay kleinanzeigen and content loads, etc.
> 
> edit: or so it seems. After killing the app a second time the previous bug appears again. So nvm my comment...

I concur. With the update `0.2.23.214816`, it seems to work fine.

**Comment by nevexc** [comment]
Had the same problem. First i tracked it down to being an Android Webview problem in combination with microG and ebay-KA.
To make a long story short, the frozen Index page and other ebay KA issues were solved by getting rid of FakeStore. 
I guess the app does some calls to vending that FakeStore does not support. Don't have logs anymore though.

**Comment by SpaceAgeHero** [comment]
Updated microG to 0.2.23.214816. Updated ebay KA. Start page still doesn't respond to touch / presses. Scrolling works.
When I jump in from a notification though, I can navigate just fine. Don't have and never had Fake Store installed. For you guys its still working fine?

**Comment by phrogg** [comment]
> Updated microG to 0.2.23.214816. Updated ebay KA. Start page still doesn't respond to touch / presses. Scrolling works. When I jump in from a notification though, I can navigate just fine. Don't have and never had Fake Store installed. For you guys its still working fine?

Same here, I looked for the fakestore in all app list but I cannot seem to find it. Maybe it is part of microg? I also still have the same issues.

**Comment by coxtor** [comment]
For now my described fix here still works fine:
https://github.com/microg/GmsCore/issues/1151#issuecomment-829571248

**Comment by phrogg** [comment]
> For now my described fix here still works fine: [#1151 (comment)](https://github.com/microg/GmsCore/issues/1151#issuecomment-829571248)

Ok I tried this four times in the past it never worked for me. I either had the same issue or some issue with shelter ehich couldnt start the ebay app at all.

**Comment by coxtor** [comment]
Interessting, by now I am on the latest version (13204) and it continues to work. Needless to say that I don't have microg in the work profile and have not installed ebay kleinanzeigen in the main profile? Still on a Pixel 4a 5G running calyx os on Android 12 using microg 0.2.22.214516-37 (ed7473d)

**Comment by phrogg** [comment]
> Interessting, by now I am on the latest version (13204) and it continues to work. Needless to say that I don't have microg in the work profile and have not installed ebay kleinanzeigen in the main profile? Still on a Pixel 4a 5G running calyx os on Android 12 using microg 0.2.22.214516-37 (ed7473d)

Thanks I think I tried all of that. Im just unsure If I uninstalled kleinanzeigen on my main profile. However I used App cloner and got it to running with using the option "Hide Google Play Services".

**Comment by coxtor** [comment]
I'm not sure how app cloner works as I have not used it before, but shelter makes use of the android work profile and apps are truly isolated, such an option like you described is not available. Have you tried it with shelter?

**Comment by phrogg** [comment]
> I'm not sure how app cloner works as I have not used it before, but shelter makes use of the android work profile and apps are truly isolated, such an option like you described is not available. Have you tried it with shelter?



> > For now my described fix here still works fine: [#1151 (comment)](https://github.com/microg/GmsCore/issues/1151#issuecomment-829571248)
Yes like I said it didn't work for me...
> Ok I tried this four times in the past it never worked for me. I either had the same issue or some issue with shelter ehich couldnt start the ebay app at all.

**Comment by obifur** [comment]
> > I'm not sure how app cloner works as I have not used it before, but shelter makes use of the android work profile and apps are truly isolated, such an option like you described is not available. Have you tried it with shelter?
> 
> > > For now my described fix here still works fine: [#1151 (comment)](https://github.com/microg/GmsCore/issues/1151#issuecomment-829571248)
> 
> Yes like I said it didn't work for me...
> 
> > Ok I tried this four times in the past it never worked for me. I either had the same issue or some issue with shelter ehich couldnt start the ebay app at all.

Did you deactivate microg as I mentioned before?

**Comment by phrogg** [comment]
> > > I'm not sure how app cloner works as I have not used it before, but shelter makes use of the android work profile and apps are truly isolated, such an option like you described is not available. Have you tried it with shelter?
> > 
> > 
> > > > For now my described fix here still works fine: [#1151 (comment)](https://github.com/microg/GmsCore/issues/1151#issuecomment-829571248)
> > 
> > 
> > Yes like I said it didn't work for me...
> > > Ok I tried this four times in the past it never worked for me. I either had the same issue or some issue with shelter ehich couldnt start the ebay app at all.
> 
> Did you deactivate microg as I mentioned before?

Yes

**Comment by deraljoscha** [comment]
Same problem still consistent under Lineage OS 19.1 (beyond0lte)

**Comment by obifur** [comment]
It's working for me now. There's only some delay of a few seconds before I'm able to press the buttons of the sidebar after open the app.

Please try an confirm. My setup:

CrDroid 7.19 (LOS 18.1)
ebay Kleinanzeigen 13.22.0
microG 0.2.24.214816

most likely irrelevant:
I activated zygisk and put "microG service core" to the deny list in magisk.

**Comment by Octo80** [comment]
I can confirm that sometimes buttons/links are working - partly after a short delay.

But sometimes there is still no reaction after a press on a link/button.

My setup:
CalyxOs 3.7.0 (Android 12)
ebay Kleinanzeigen 13.22.0
microG 0.2.24.214816-25

**Comment by gitfineon** [comment]
Looks like it may depend on the device or ROM, rather than microG or OS version. There are no issues with OnePlus One (bacon) https://github.com/microg/GmsCore/issues/1151#issuecomment-848231718 , OnePlus 3 (oneplus3), OnePlus 8 (instantnoodle) and Google Pixel 4a (sunfish).

We've seen issues with BQ Aquaris X (bardock), Xiaomi Redmi Note 5 Pro (whyred), Samsung Galaxy S7 Edge (hero2lte) and Samsung Galaxy S10e (beyond0lte).

 I've installed [TrackerControl](https://f-droid.org/packages/net.kollnig.missioncontrol.fdroid/) some month ago, and since then the chance to click anything on the default page increased a lot. So I guess it has something to do with out-going request. So I'm no using the latest build of the app and have it works fine as long as you avoid the main page. On the main page I have to tap multiple times to select, but then it works.

**Comment by phrogg** [comment]
Yes thanks for reminding me, I can confirm it works as well, I wouldn't say flawless yet. I stilk have some minor issues with long loading times duplicates of sending messages, but I don't knkw if this is just the app itself. This has been like this for some months now, even way before they changed the name to "Kleinanzeigen". Sometimes with new updates there are small issues last week for example the map didn't work and I wasn't able to select a location and perimeter. But right now it works.

**Comment by gitfineon** [comment]
Confirm, that most of the issues reported here are no longer true for recent versions of the Kleinanzeigen app. I can also confirm that recently there was an issue with the map integration on some devices. I have not yet checked if the problem is solved for those.

Sadly I noticed that the number of trackers increased, too. They added IAB Open Measurement and Amzn Ad libraries. The first one introduces a lot of other third parties involved now. But I guess most of the activities are now tunneled through their domain, to make it harder to block. What still shows up using [TrackerControl](https://f-droid.org/packages/net.kollnig.missioncontrol.fdroid/) is the fingerprinting of online-metrix.net. I'm curious to see if others show up although I declined everything.

They also added a new IP Blocking thing for login, which makes it sometimes impossible to login from mobile network, because the entire IP range is blocked. Even from your home network you may need to confirm your login attempt with an eMail Link, if you are using private or temporary containers for tabs.

Push notification is still not reliable, but okish. Think it is no longer a issue in the app rather the entire service has those limitations.
