### ISSUE TITLE
Chrome can't login Google account

### ISSUE THREAD

**Issue by chr56** [microg/android_packages_apps_GmsCore#706]
I can't login Google account in chrome v72 : 
* First  Other Gapp can login account that has existed in system setting>account ;
* Second  When I try to log in account , it gives me a "Sign in "screen of MicroG instead of log in instantly account which is existed  in system setting >account(because I have already logged in system).
* Third So, I tried to log in account by MicroG "Sign in"page,but it said that this account has existed already!(of course, I have logged in Google account, in system setting>account)

**Comment by patrickdrd** [comment]
have you given permissions to the chrome app to read your contacts etc?

**Comment by alphajoza** [comment]
I'm using NanoDroid-microG-20.8.20190504 and can confirm the exact issue that the op mentioned and giving permissions to chrome doesn't obviate the problem.

**Comment by Vavun** [comment]
Hello @mar-v-in 

Could you please check this issue too?

This issue is critical for many users.

The problem is still exists on test custom build with latest commits

PS

https://github.com/microg/android_packages_apps_GmsCore/issues/770 fixed with latest commits

**Comment by ale5000-git** [comment]
The problem should be fixed and new version is released.
If there is any other problem, please report it.

**Comment by erik9012** [comment]
> The problem should be fixed and new version is released.
> If there is any other problem, please report it.

Still not working. Whatsapp cant vind the accoun with Android 10 lineageos microg
